[package]
name = "quic-tcp-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive"] }
futures = "0.3.31"
quinn = "0.11.8"
rustls = "0.23.31"
tokio = { version = "1.47.1", features = ["full"] }
